### ISSUE TITLE
Couldn't find token for the bot, shutting down!

### ISSUE THREAD

**Issue by Nikralx** [Chenkail/White-Rabbit#43]
I'm having an issue where when I try to run the bot I get the error
"Couldn't find token for the bot, shutting down!"
The token.txt file is located in the "White-Rabbit-master" folder. Even tried other folders. The token is placed in the file with 1 line. 
What is happening?

**Comment by Chenkail** [comment]
Hi,
Does this solve your problem? https://github.com/Rapptz/discord.py/issues/4159

**Comment by Nikralx** [comment]
This worked https://github.com/Rapptz/discord.py/issues/4159#issuecomment-709876689

**Comment by Chenkail** [comment]
Do you mind if I ask how you found this repository? I never posted links to it anywhere and now suddenly multiple people have interacted with it

**Comment by Nikralx** [comment]
The Alice is Missing Discord Template has a link to this template.
![image](https://user-images.githubusercontent.com/21001062/101201495-d6369500-3635-11eb-9022-70863f7b8f57.png)

**Comment by Chenkail** [comment]
Huh okay, where did you find the template?

**Comment by Nikralx** [comment]
On the Alice is Missing Main webpage https://www.huntersentertainment.com/alice-is-missing

**Comment by Nikralx** [comment]
Nevermind it's a different template. It might have been from a google search.

**Comment by Chenkail** [comment]
Huh. I never thought anyone would find this - I made it as a side project to run Alice with my friends. Let me know if you run into any other issues, I'm glad other people like the game as much as I do

**Comment by Nikralx** [comment]
Only ran into 2 issues with our first play through.
1) Evan role was not give to the Evan player when claimed despite bot saying so. 
2) When assigning Clues, it appears everyone has to be in Voice Chat? Took us a bit to figure that out as one person wasn't getting any clues until they joined. 

Otherwise the bot helped a lot with the flow of the game! The PDF came out beautifully. Thanks so much for making this. 

Not a big deal but having some sort of Voicemail option would be cool, otherwise we just used a voice recorder website and played them back.

**Comment by Chenkail** [comment]
Hi,
1. Was the person playing Evan the owner of the server? The bot is unable to change roles/nicknames for server owners due to how discord permissions work.
2. I think this should be fixed in the latest version? Someone else had that issue and submitted a pull request.
3. The way I've had the bot handle voicemails was by having the players type spoilered messages into the #voicemails channel in the server, then reading them out loud at the end of the game. This allows the bot to pick up the text and insert them into the PDF (you can still do this after the game has ended! Just have each player type their voicemail in and run !pdf again)

**Comment by Chenkail** [comment]
For the second issue, you will have to enable the Server Members privileged gateway intent in the discord developer portal as well as downloading the latest copy of the bot

**Comment by Nikralx** [comment]
1. No it wasn't
2. I will have to check next time.

**Comment by Chenkail** [comment]
Hmm, okay. I don't know if I can find the issue without more information, but I'll take a look. Let me know if it happens again
