### ISSUE TITLE
Thanks for making this!

### ISSUE THREAD

**Issue by Veraticus** [Chenkail/White-Rabbit#45]
I found this by Googling for a Discord Alice is Missing bot and I'm really glad it exists. Keep up the good work!

**Comment by TakaraGEG** [comment]
This looks awesome but I can’t get it to start. I have done the Installation but am confused by the shell window for set up. I have tried both windows and Python but nothing is linking it to the file downloaded.

**Comment by Chenkail** [comment]
What do you mean by shell window? After running the bot, all commands should be entered through discord

**Comment by TakaraGEG** [comment]
I am having problems starting the bot. Every time I try command : $ python /path/to/src I get an error. 
ModuleNotFoundError: No module named 'discord'

**Comment by Chenkail** [comment]
You need to install discord through text - try
```shell
pip install -r requirements.txt
```
