### ISSUE TITLE
certificate has expired (_ssl.c:1123) When attempting to start bot

### ISSUE THREAD

**Issue by cmorris05** [Chenkail/White-Rabbit#48]
I have downloaded both discord.py and fpdf, and I am still getting an error.

Here is the list of modules I have loaded:

Package           Version
----------------- -------
aiohttp           3.7.3
async-timeout     3.0.1
attrs             20.3.0
chardet           3.0.4
discord.py        1.6.0
fpdf              1.7.2
idna              3.1
multidict         5.1.0
typing-extensions 3.7.4.3
yarl              1.6.3

This is the line with the error that shows the certificate has expired.

  raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')]

**Comment by Chenkail** [comment]
Hi,
Does this solve your problem? https://github.com/Rapptz/discord.py/issues/4159

**Comment by cmorris05** [comment]
It did, but I was not quite sure why I needed to export and save off the discord cert for the script to work.

**Comment by Chenkail** [comment]
It's not an issue with the bot. A security certificate expired so the server won't allow the bot to connect.
